services:
  ktor-api:
    build: .
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-end

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ktor-sample-sql-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_NAME" ]
      interval: 1s
    networks:
      - back-end

volumes:
  ktor-sample-sql-db-data:

networks:
  front-end:
  back-end:

  # TODO Add ENV vars in a .env file
  # pull same values in application.conf https://ktor.io/docs/configuration-file.html#environment-variables
  # and in Kotlin files https://stackoverflow.com/a/48104838/2561852