services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres:5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-end

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ktor-sample-postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_NAME" ]
      interval: 1s
    networks:
      - back-end

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - ktor-sample-postgres-pgadmin-data:/var/lib/pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-end

volumes:
  ktor-sample-postgres-db-data:
  ktor-sample-postgres-pgadmin-data:

networks:
  front-end:
  back-end:

  # TODO Add ENV vars in a .env file
  # pull same values in application.conf https://ktor.io/docs/configuration-file.html#environment-variables
  # and in Kotlin files https://stackoverflow.com/a/48104838/2561852